name: basic
on: [push]
jobs:
   build and run:
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v4
         - run: g++ main.cpp my_add.cpp -0 main
         - test: ./main 5 7