name: build and run
on: [push]
jobs:
   build and run:
      runs-on: ubuntu-latest
      stages: 
         - uses: actions/checkout 
         - run: g++ main.cpp my_add.cpp -0 main
         - test: ./main 5 7